name: continuous-integration

on:
  pull_request:
    branches: [ '**' ]

  workflow_dispatch:

jobs:

  test:

    name: Test Codebase
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
            dotnet-version: '5.0.x'
      - run: 
          ls
          dotnet build ZRD

      - name: Run 'dotnet test'
        id: dotnet-test
        run: dotnet test 